spring.application.name=product

spring.datasource.url=jdbc:postgresql://db.smmdhwkrmbfddreknzwx.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=WTfX6Ofk22a9l4T7

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# REDIS CONFIG
spring.data.redis.host=localhost
spring.data.redis.port=6379

# SECURITY (disable default login)
spring.security.user.name=admin
spring.security.user.password=admin

# CONNECTION POOL FIX
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000

spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=30000

# VERY IMPORTANT (prevents dead connections)
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.keepalive-time=15000
spring.datasource.hikari.connection-test-query=SELECT 1

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=teambuildurskill@gmail.com
spring.mail.password=usdm rsvb czup vnrf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true